eclipse-ee4j/jakartaee-tck-tools

- tools/extract-spec-assertions/build.xml
- tools/extract-spec-assertions/src/com/oracle/ts/tools/extractor/pdf/Driver.java
This change removed the pdfbox-app-jar reference and replaced it with 3 other jars in the build script.
> update the jar pdfbox and other jar refs in extract-spec-assertions tool

- jobs/common/backup.sh
- jobs/eftl-jakartaeetck-build-900/publish.sh
In this PR there is a new `jobs` directory where we can put the scripts we've been using for the various jobs so they are revision controlled.  This also could greatly reduce duplication.  If we like the pattern, I'll move all the scripts over.
There is also a reusable script that can create a history of past builds so we have a bit of retention (5 builds).  If a particular build of the TCK results in a passing run, the project can indicate by SHA which TCK they want promoted.
- https://download.eclipse.org/ee4j/jakartaee-tck/jakartaee9-eftl/staged-900/history/
> Improve `eftl-jakartaeetck-build-900` job so it keeps a history

- jobs/common/backup.sh
- jobs/eftl-jakartaeetck-build-900/publish.sh
This should allow us to keep an unlimited number of Platform TCK zips in history for a little while (until we release EE 9).
> temporarily remove the max number of backups

- tools/tck-rewrite/pom.xml
- tools/tck-rewrite/src/main/java/tck/jakarta/platform/rewrite/AddArquillianDeployMethod.java
- tools/tck-rewrite/src/main/java/tck/jakarta/platform/rewrite/ConvertJavaTestNameRecipe.java
- tools/tck-rewrite/src/main/java/tck/jakarta/platform/rewrite/ConvertJavaTestNameVisitor.java
- tools/tck-rewrite/src/main/java/tck/jakarta/platform/rewrite/JavaTestToArquillianShrinkwrap.java
- tools/tck-rewrite/src/main/java/tck/jakarta/platform/rewrite/Main.java
- tools/tck-rewrite/src/test/java/tck/conversion/rewrite/AddArqDeploymentTest.java
- tools/tck-rewrite/src/test/java/tck/conversion/rewrite/JavaTestToArqTest.java
- tools/tck-rewrite/src/test/java/tck/conversion/rewrite/LargeCaseAfter.java
- tools/tck-rewrite/src/test/java/tck/conversion/rewrite/LargeCaseBefore.java
- tools/tck-rewrite/src/test/resources/logging.properties
I was testing against changes in the openrewrite maven plugin and found that the latest code requires the 8.7.x version of openrewrite core due to incompatible changes, so this updates to 8.7.2.
> Update the rewrite rules to use openrewrite 8.7.2

- tools/sigtest/pom.xml
- tools/sigtest/src/main/java/com/sun/tdk/signaturetest/classpath/Release.java
- tools/sigtest/src/test/java/com/sun/tdk/signaturetest/classpath/ReleaseTest.java
The current way of only using data from the version this project was compiled on does not work when you want to run against newer JVM's. For example errors like `Fatal error: class java.lang.annotation.Annotation not found` are reported because the `com.sun.tdk.signaturetest.classpath.Release` cannot be found.
This change uses the local `${java.home}/lib/ct.sym` to determine the signature files.
resolves #22
> Fix the sigtest Release to allow for new JVM's

- tools/tck-rewrite/src/main/java/tck/jakarta/platform/rewrite/Main.java
change relative (result) path to absolute path which helps with running `mvn compile exec:java -Dexec.mainClass="tck.jakarta.platform.rewrite.Main" -Dexec.args="-include /home/me/platformtck/jdbc -class Client -package com.sun.ts.tests.jdbc -run"  `
Without this change, result.getAfter().getSourcePath() returned a relative path to the output that which led to a file not found error.
> change relative (result) path to absolute path 

- tools/sigtest/README.md
- tools/sigtest/pom.xml
- tools/sigtest/src/main/java/com/sun/tdk/signaturetest/Merge.java
- tools/sigtest/src/main/java/com/sun/tdk/signaturetest/Setup.java
- tools/sigtest/src/main/java/com/sun/tdk/signaturetest/SetupAndTest.java
- tools/sigtest/src/main/java/com/sun/tdk/signaturetest/SigTest.java
- tools/sigtest/src/main/java/com/sun/tdk/signaturetest/SignatureTest.java
- tools/sigtest/src/main/java/com/sun/tdk/signaturetest/core/ClassCorrector.java
- tools/sigtest/src/main/java/com/sun/tdk/signaturetest/core/JDKExclude.java
- tools/sigtest/src/main/java/com/sun/tdk/signaturetest/core/MemberCollectionBuilder.java
- tools/sigtest/src/main/java/com/sun/tdk/signaturetest/core/ThrowsNormalizer.java
- tools/sigtest/src/main/java/org/netbeans/apitest/Sigtest.java
- tools/sigtest/src/main/java/org/netbeans/apitest/SigtestCheck.java
- tools/sigtest/src/main/java/org/netbeans/apitest/SigtestCompare.java
- tools/sigtest/src/main/java/org/netbeans/apitest/SigtestGenerate.java
- tools/sigtest/src/main/java/org/netbeans/apitest/SigtestHandler.java
Work in progress for https://github.com/eclipse-ee4j/jakartaee-tck-tools/issues/20.  This change eliminates the need for passing the often changing list JDK classes to exclude.  Instead just set -IgnoreJDKClass
> Ensure that sigtest -IgnoreJDKClass can ignore JDK classes (java.* and javax.transaction.xa.*) during signature check

- tools/sigtest/pom.xml
- tools/sigtest/src/main/java/com/sun/tdk/signaturetest/Version.java
- tools/sigtest/src/test/java/com/sun/tdk/signaturetest/VersionIT.java
- tools/sigtest/src/test/resources/VersionIT.properties
- Update the com.sun.tdk.signaturetest.Version class to get version info from the artifact jar manifest.
- Remove the obsolete release profile used in jboss fork
- Fixes #33
> Restore build version information

- tools/tck-rewrite-ant/src/main/java/tck/jakarta/platform/ant/api/TestPackageInfoBuilder.java
Address https://github.com/eclipse-ee4j/jakartaee-tck-tools/issues/72
> issue:72 tck-rewrite-ant (TestPackageInfoBuilder) needs additional mappings for Mappings from EE11 to EE10 package prefixes for Persistence

- tools/tck-rewrite-ant/src/main/java/tck/jakarta/platform/ant/api/TestPackageInfoBuilder.java
Address https://github.com/eclipse-ee4j/jakartaee-tck-tools/issues/78
With this change, I no longer get `WARNING: TODO: src/main/java/com/sun/ts/tests/ejb30/lite/tx/cm/stateful/webrw/ClientEjbliteservletTest.java was already previously generated which means we aren't handling something correctly.` warnings when transforming the ejb30 tests.
> issue 78, Generate JsfClientEjblitejsfTest.java for input JsfClient.java instead of ClientEjblitejsfTest.java which conflicts with input Client.java

- tools/tck-rewrite/src/main/java/tck/jakarta/platform/rewrite/GenerateNewTestClassRecipe.java
https://github.com/eclipse-ee4j/jakartaee-tck-tools/issues/80 Fix empty test method problem by using improved comment parsing like tck-rewrite-fx JavaTestNameVisitor test is doing
> issue 80, Fix empty test method problem 

- tools/tck-rewrite-ant/src/main/java/tck/jakarta/platform/ant/api/DefaultEEMapping.java
- tools/tck-rewrite-ant/src/test/java/tck/conversion/ant/api/DefaultMappingsTest.java
Generalize the ee11 testClass mapping so that the ClientN class and any inner classes are mapped
Fixes #97
> Generalize the ee11 testClass mapping

- tools/tck-rewrite-ant/pom.xml
- tools/tck-rewrite-ant/src/main/java/tck/jakarta/platform/ant/TsTaskListener.java
- tools/tck-rewrite-ant/src/main/java/tck/jakarta/platform/ant/api/TestPackageInfoBuilder.java
- tools/tck-rewrite-ant/src/test/java/tck/conversion/ant/api/DeploymentMethodTest.java
- tools/tck-rewrite/pom.xml
- tools/tck-rewrite/src/main/java/tck/jakarta/platform/rewrite/GenerateNewTestClassRecipe.java
Add a overwriteExistingTests flag to GenerateNewTestClassRecipe Correct a failure when a copy inside the package target was seen
> Correct arquillian dependency to 1.9.1.Final

- tools/tck-rewrite/src/main/java/tck/jakarta/platform/rewrite/GenerateNewTestClassRecipe.java
Interesting that order is important as this doesn't truncate the output file:
> Files.writeString(testClientJavaFile, testClient.getContent(), StandardOpenOption.CREATE, StandardOpenOption.WRITE, StandardOpenOption.TRUNCATE_EXISTING)
But this does truncate the output file:
> Files.writeString(testClientJavaFile, testClient.getContent(), StandardOpenOption.CREATE, StandardOpenOption.TRUNCATE_EXISTING, StandardOpenOption.WRITE)
^ makes sense that the parameters are processed in order
> issue 105, Truncate output files when using tck-rewrite overwriteExistingTests

- tools/tck-rewrite-ant/pom.xml
- tools/tck-rewrite-ant/src/main/java/tck/jakarta/platform/ant/api/TestPackageInfoBuilder.java
- tools/tck-rewrite-ant/src/test/java/tck/conversion/CompareTestRuns.java
- tools/tck-rewrite-ant/src/test/java/tck/conversion/ant/api/DeploymentMethodTest.java
> Change the handling of the ejblitejsf vehicle type

- tools/tck-rewrite-ant/src/main/resources/TsPar.stg
https://github.com/eclipse-ee4j/jakartaee-tck-tools/issues/140
The following additional mapping handling is added for all persistence.xml specifically if we detect a myMappingFile.xml file:
```
if(parURL != null) {
jpa_core_EntityGraph.addAsResource(parURL, "persistence.xml");
}
// Add the Persistence mapping-file
URL mappingURL = Client.class.getResource("myMappingFile.xml");
if(mappingURL != null) {
jpa_core_EntityGraph.addAsResource(mappingURL, "myMappingFile.xml");
}
mappingURL = Client.class.getResource("myMappingFile1.xml");
if(mappingURL != null) {
jpa_core_EntityGraph.addAsResource(mappingURL, "myMappingFile1.xml");
}
mappingURL = Client.class.getResource("myMappingFile2.xml");
if(mappingURL != null) {
jpa_core_EntityGraph.addAsResource(mappingURL, "myMappingFile2.xml");
}
```
> tck-rewrite-ant: Persistence mapping-file (e.g. myMappingFile.xml) files are not added to deployments #140

- arquillian/common/src/main/java/tck/arquillian/protocol/common/TsTestPropsBuilder.java
https://github.com/eclipse-ee4j/jakartaee-tck-tools/issues/145
For properties like ts.home, if they are not found in the ts.jte, look in system properties.
> Arquillian should check for system property if ts.home is not set in ts.jte file issues/145

- arquillian/common/src/main/java/tck/arquillian/protocol/common/TsTestPropsBuilder.java
The EL tests fail with missing property variable.mapper that is read from ts.jte file.
> Add tsjte property variable.mapper used for EL tests

- arquillian/common/src/main/java/tck/arquillian/protocol/common/TsTestPropsBuilder.java
Correction for reopened https://github.com/eclipse-ee4j/jakartaee-tck-tools/issues/145 in response to feedback on https://github.com/eclipse-ee4j/jakartaee-tck-tools/pull/146 (e.g. actually sets the property value variable).
Also ensures we don't try to put a null property which gets a NPE and adds an additional system property check.
> Arquillian correction/improvement for check for system property if ts.home is not set in ts.jte file issues/145

- .github/workflows/sigtest-ci.yml
- tools/sigtest/pom.xml
- tools/sigtest/src/main/java/com/sun/tdk/signaturetest/classpath/Release.java
- tools/sigtest/src/test/java/com/sun/tdk/signaturetest/classpath/ReleaseTest.java
resolves #35 
This also adds some CI and refactored the `ReleaseTest` to be more dynamic.
> [35] Allow newer JVM's to be used with the Release argument

- arquillian/common/src/main/java/tck/arquillian/protocol/common/TsTestPropsBuilder.java
This property is only used in the `com.sun.ts.tests.signaturetest.SigTestData.getCurrentKeywords()`. However, that method is never used.
> Remove the unused signature test properties.

- arquillian/appclient/src/main/java/tck/arquillian/protocol/appclient/AppClientMethodExecutor.java
In testing with Open Liberty, app client tests were returning status like the following:
[err] STATUS:
[err] Passed.
Because it is split between two lines, the status parsing logic was not able to determine what the result was. I've added a case that will handle this scenario while maintaining support for the original case.
> Support Two-Line AppClient Test Status
