jobs/eftl-jakartaeetck-build-901/publish.sh
Signed-off-by: Scott Marlow <smarlow@redhat.com>
=> add script for use with https://ci.eclipse.org/jakartaee-tck/job/eftl-jakartaeetck-build-901 for the Jakarta EE Platform TCK 9.0.1

tools/jar2shrinkwrap/src/main/java/jakartatck/jar2shrinkwrap/AbstractFileProcessor.java, tools/tck-rewrite/src/test/java/tck/conversion/rewrite/AddArqDeploymentTest.java, tools/tck-rewrite/src/test/java/tck/conversion/rewrite/JavaTestToArqTest.java
With this the tck-rewrite module is building correctly
=> Fix an addClass in jar2shrinkwrap and update tck-rewrite tests

tools/sigtest/src/main/java/com/sun/tdk/signaturetest/core/Erasurator.java
=> [26] Remove the debug assertion as it could break on valid signatures.

tools/tck-rewrite-ant/src/main/java/tck/jakarta/platform/ant/api/TestClientFile.java, tools/tck-rewrite-ant/src/main/java/tck/jakarta/platform/ant/api/TestClientInfo.java, tools/tck-rewrite-ant/src/main/java/tck/jakarta/platform/ant/api/TestPackageInfo.java, tools/tck-rewrite-ant/src/test/java/tck/conversion/ant/api/DeploymentMethodTest.java
=> Improve the api for accessing the generated test client java file

tools/tck-rewrite-ant/src/main/java/tck/jakarta/platform/ant/BaseJar.java, tools/tck-rewrite-ant/src/main/java/tck/jakarta/platform/ant/PackageTarget.java, tools/tck-rewrite-ant/src/main/java/tck/jakarta/platform/ant/Rar.java, tools/tck-rewrite-ant/src/main/java/tck/jakarta/platform/ant/TSFileSet.java, tools/tck-rewrite-ant/src/main/java/tck/jakarta/platform/ant/TsTaskListener.java, tools/tck-rewrite-ant/src/main/java/tck/jakarta/platform/ant/api/DeploymentInfo.java, tools/tck-rewrite-ant/src/main/java/tck/jakarta/platform/ant/api/TestClientFile.java, tools/tck-rewrite-ant/src/main/java/tck/jakarta/platform/ant/api/TestPackageInfoBuilder.java, tools/tck-rewrite-ant/src/main/resources/DeploymentMethod.stg, tools/tck-rewrite-ant/src/main/resources/TsRar.stg, tools/tck-rewrite-ant/src/test/java/tck/conversion/FixTCKTemplates.java, tools/tck-rewrite-ant/src/test/java/tck/conversion/ant/api/DeploymentMethodTest.java, tools/tck-rewrite-ant/src/test/java/tck/conversion/ant/st4/DeploymentRecord.java, tools/tck-rewrite-ant/src/test/java/tck/conversion/ant/st4/StringTemplateTests.java, tools/tck-rewrite-ant/src/test/resources/StringTemplate4Tests.stg, tools/tck-rewrite-fx/src/main/java/tck/jakarta/rewrite/fx/AppController.java, tools/tck-rewrite-fx/src/main/java/tck/jakarta/rewrite/fx/codeview/JavaTestNameVisitor.java, tools/tck-rewrite-fx/src/main/java/tck/jakarta/rewrite/fx/dirview/FileTreeItem.java, tools/tck-rewrite-fx/src/main/resources/fxml/app.fxml, tools/tck-rewrite-fx/src/main/resources/logging.properties
Signed-off-by: Scott M Stark <starksm64@gmail.com>
#51
=> Fix the archiveName is null failure.

arquillian/common/src/main/java/tck/arquillian/protocol/common/TsTestPropsBuilder.java, arquillian/pom.xml, arquillian/porting-lib/pom.xml, arquillian/porting-lib/src/main/java/tck/arquillian/porting/lib/spi/AbstractTestArchiveProcessor.java, arquillian/porting-lib/src/main/java/tck/arquillian/porting/lib/spi/TestArchiveProcessor.java
https://github.com/jakartaee/platform-tck/issues/1355
=> An initial suggesting for the porting lib spi

tools/tck-rewrite-ant/pom.xml, tools/tck-rewrite-ant/src/main/java/tck/jakarta/platform/ant/api/TestPackageInfoBuilder.java, tools/tck-rewrite-ant/src/test/java/tck/conversion/ant/api/DeploymentMethodTest.java, tools/tck-rewrite-fx/src/main/java/tck/jakarta/rewrite/fx/AppController.java, tools/tck-rewrite-fx/src/main/resources/fxml/app.fxml
Deal with EE11 test classes that have changed package prefixes
=> Add EE11 to EE10 package mapping

tools/tck-rewrite-fx/src/main/java/tck/jakarta/rewrite/fx/AppController.java
Resolves test compile error when building tck-rewrite-fx
=> Add EE11toEE10Mapping to tools/tck-rewrite-fx/src/main/java/tck/jakarta/rewrite/fx/AppController.java test

tools/tck-rewrite-ant/src/main/java/tck/jakarta/platform/ant/api/KeywordTags.java, tools/tck-rewrite-ant/src/main/java/tck/jakarta/platform/ant/api/TestClientInfo.java, tools/tck-rewrite-ant/src/main/java/tck/jakarta/platform/ant/api/TestPackageInfoBuilder.java, tools/tck-rewrite-ant/src/main/resources/ArqClientTest.stg, tools/tck-rewrite-ant/src/main/resources/TsClientJar.stg, tools/tck-rewrite-ant/src/main/resources/TsEar.stg, tools/tck-rewrite-ant/src/main/resources/TsEjbJar.stg, tools/tck-rewrite-ant/src/main/resources/TsRar.stg, tools/tck-rewrite-ant/src/main/resources/TsWar.stg, tools/tck-rewrite-ant/src/main/resources/keyword.properties, tools/tck-rewrite-ant/src/test/java/tck/conversion/ant/api/KeywordTagTest.java
https://github.com/jakartaee/platform-tck/issues/1428
=> Map the keyword.properties to Junit5 @Tag(s)

tools/tck-rewrite-ant/src/main/java/tck/jakarta/platform/ant/api/DefaultEEMapping.java
Also add this mapping for package rename previously done for EE 11 standalone Persistence tck
=> also map ee.jakarta.tck.persistence.core.persistenceUnitUtil + com.sun.ts.tests.jpa.core.persistenceUtilUtil

tools/tck-rewrite/src/main/java/tck/jakarta/platform/rewrite/GenerateNewTestClassRecipe.java
https://github.com/eclipse-ee4j/jakartaee-tck-tools/issues/84
=> Also parse OpenRewrite Javadoc comment class as well as remove duplicate methodNames

tools/tck-rewrite-ant/src/main/java/tck/jakarta/platform/ant/api/TestPackageInfoBuilder.java, tools/tck-rewrite-ant/src/main/resources/DeploymentMethod.stg, tools/tck-rewrite-ant/src/test/java/tck/conversion/ant/TsArtifactsTest.java, tools/tck-rewrite-ant/src/test/java/tck/conversion/ant/api/DeploymentMethodTest.java
=> Add the missing par generation code to the genMethodNonVehicle

tools/tck-rewrite-ant/src/main/java/tck/jakarta/platform/ant/Lib.java, tools/tck-rewrite-ant/src/main/java/tck/jakarta/platform/ant/PackageTarget.java, tools/tck-rewrite-ant/src/main/java/tck/jakarta/platform/ant/Utils.java, tools/tck-rewrite-ant/src/main/java/tck/jakarta/platform/ant/Vehicles.java, tools/tck-rewrite-ant/src/main/java/tck/jakarta/platform/ant/api/DefaultEEMapping.java, tools/tck-rewrite-ant/src/main/java/tck/jakarta/platform/ant/api/EE11toEE10Mapping.java, tools/tck-rewrite-ant/src/main/java/tck/jakarta/platform/ant/api/TestPackageInfoBuilder.java, tools/tck-rewrite-ant/src/test/java/tck/conversion/ant/api/DefaultMappingsTest.java, tools/tck-rewrite-ant/src/test/java/tck/conversion/ant/api/DeploymentMethodTest.java
=> Deal with test class file rename

arquillian/javatest/pom.xml, arquillian/pom.xml, arquillian/protocol-lib/pom.xml
Create a specific protocol-lib artifact
=> Remove javatest dependency

tools/tck-rewrite-ant/src/main/java/tck/jakarta/platform/ant/TsFileSet.java, tools/tck-rewrite-ant/src/main/java/tck/jakarta/platform/ant/TsTaskListener.java, tools/tck-rewrite-ant/src/main/java/tck/jakarta/platform/ant/Vehicles.java, tools/tck-rewrite-ant/src/main/java/tck/jakarta/platform/ant/War.java, tools/tck-rewrite-ant/src/main/java/tck/jakarta/platform/ant/api/DeploymentInfo.java, tools/tck-rewrite-ant/src/main/java/tck/jakarta/platform/ant/api/TestPackageInfoBuilder.java, tools/tck-rewrite-ant/src/main/resources/TsClientJar.stg, tools/tck-rewrite-ant/src/main/resources/TsEar.stg, tools/tck-rewrite-ant/src/main/resources/TsEjbJar.stg, tools/tck-rewrite-ant/src/main/resources/TsPar.stg, tools/tck-rewrite-ant/src/main/resources/TsRar.stg, tools/tck-rewrite-ant/src/main/resources/TsWar.stg, tools/tck-rewrite-ant/src/test/java/tck/conversion/FixTCKJspTemplates.java, tools/tck-rewrite-ant/src/test/java/tck/conversion/ant/TsArtifactsTest.java, tools/tck-rewrite-ant/src/test/java/tck/conversion/ant/api/DeploymentMethodTest.java
Add jsp vehicle tld files
Fixes #107
=> Improve war content collection

tools/tck-rewrite-ant/src/main/java/tck/jakarta/platform/ant/api/TestPackageInfoBuilder.java, tools/tck-rewrite-ant/src/main/resources/ArqClientTest.stg
=> Sort test methods alphabetically to match the EE10 behavior

tools/tck-rewrite/src/main/java/tck/jakarta/platform/rewrite/GenerateNewTestClassRecipe.java
https://github.com/eclipse-ee4j/jakartaee-tck-tools/issues/117
=> issue 117 tck-rewrite is not transforming tests under jjms/src/main/java/com/sun/ts/tests/jms/core

tools/tck-rewrite-ant/src/main/java/tck/jakarta/platform/ant/TsFileSet.java, tools/tck-rewrite-ant/src/main/java/tck/jakarta/platform/ant/Utils.java, tools/tck-rewrite-ant/src/main/java/tck/jakarta/platform/ant/api/DefaultEEMapping.java, tools/tck-rewrite-ant/src/main/java/tck/jakarta/platform/ant/api/EE11toEE10Mapping.java, tools/tck-rewrite-ant/src/main/java/tck/jakarta/platform/ant/api/TestPackageInfoBuilder.java, tools/tck-rewrite-ant/src/main/resources/DeploymentMethod.stg, tools/tck-rewrite-ant/src/main/resources/TsEjbJar.stg, tools/tck-rewrite-ant/src/test/java/tck/conversion/ant/TsArtifactsTest.java, tools/tck-rewrite-ant/src/test/java/tck/conversion/ant/api/DeploymentMethodTest.java
=> Fix null includes in fileset

tools/tck-rewrite-ant/src/main/java/tck/jakarta/platform/ant/BaseJar.java, tools/tck-rewrite-ant/src/main/java/tck/jakarta/platform/ant/api/DefaultEEMapping.java, tools/tck-rewrite-ant/src/main/java/tck/jakarta/platform/ant/api/EE11toEE10Mapping.java, tools/tck-rewrite-ant/src/main/java/tck/jakarta/platform/ant/api/TestPackageInfoBuilder.java, tools/tck-rewrite-ant/src/test/java/tck/conversion/ant/api/DeploymentMethodTest.java
=> Add the Client base class of the ClientN test class mapping.

tools/tck-rewrite-ant/src/main/java/tck/jakarta/platform/ant/api/DefaultEEMapping.java, tools/tck-rewrite-ant/src/test/java/tck/conversion/ant/api/DeploymentMethodTest.java
=> Make sure the previous ClientN test class mapping is cleared every time.

arquillian/appclient/src/main/java/tck/arquillian/protocol/appclient/AppClientCmd.java, arquillian/appclient/src/main/java/tck/arquillian/protocol/appclient/AppClientProtocolConfiguration.java, arquillian/appclient/src/test/java/org/jboss/arquillian/protocol/AppClientConfigTest.java, arquillian/common/src/main/java/tck/arquillian/protocol/common/ProtocolCommonConfig.java, arquillian/common/src/main/java/tck/arquillian/protocol/common/TsTestPropsBuilder.java, tools/tck-rewrite-ant/src/main/java/tck/jakarta/platform/ant/PackageTarget.java, tools/tck-rewrite-ant/src/test/java/tck/conversion/ant/api/DeploymentMethodTest.java
Add missing properties used by javamail
Fixes #139
=> Fix the way the envp was passed to the appclient process

arquillian/appclient/src/main/java/tck/arquillian/protocol/appclient/AppClientCmd.java
fix for CNFE of EJB Vehicle classes
=> fix for CNFE of EJB Vehicle classes

tools/sigtest/pom.xml, tools/sigtest/src/main/java/org/netbeans/apitest/SigtestGenerate.java
https://github.com/eclipse-ee4j/jakartaee-tck-tools/issues/160
=> Release 2.5 with fix for version parameter support is broken in maven plug for generating signature map files

arquillian/appclient/pom.xml, arquillian/appclient/src/main/java/tck/arquillian/protocol/appclient/AppClientCmd.java, arquillian/appclient/src/main/java/tck/arquillian/protocol/appclient/AppClientDeploymentPackager.java, arquillian/appclient/src/main/java/tck/arquillian/protocol/appclient/AppClientMethodExecutor.java, arquillian/appclient/src/main/java/tck/arquillian/protocol/appclient/AppClientProtocol.java, arquillian/appclient/src/main/java/tck/arquillian/protocol/appclient/AppClientProtocolConfiguration.java, arquillian/appclient/src/main/java/tck/arquillian/protocol/appclient/AppClientProtocolExtension.java, arquillian/appclient/src/main/java/tck/arquillian/protocol/appclient/DeploymentMonitor.java, arquillian/appclient/src/main/java/tck/arquillian/protocol/appclient/DeploymentMonitorProvider.java, arquillian/pom.xml
=> Add a appclient protocol client stub jar generation/retrieval option.
